# Generated by Django 4.1 on 2022-08-18 02:07

from django.db import migrations
import users.manage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.manage.CustomUserManager()),
            ],
        ),
    ]
