# Generated by Django 4.1 on 2022-08-19 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_example', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='example',
            name='removed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_by_example', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='example',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_example', to=settings.AUTH_USER_MODEL),
        ),
    ]
