# Generated by Django 4.1 on 2022-08-18 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='example',
            index=models.Index(fields=['-id', '-name'], name='example_id_920004_idx'),
        ),
    ]
